on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    name: name for what
    steps:
    
      # - name: Checkout repo
      #   uses: actions/checkout@v3
      
      - name: echo message
        run: echo this is Halloween :3 and next